linters:
  AllowedScriptType:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
  ExtraNewline:
    enabled: true
  HardCodedString:
    enabled: false
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RightTrim:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/CommentIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  RubocopText:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/CommentIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  TrailingWhitespace:
    enabled: true
