require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - .git/**/*
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
Metrics/BlockLength:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
Rails:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
