# 開発環境用。本番環境では使わないこと。

version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: sh -c 'bundle && rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'
    depends_on:
      - mailhog
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: appname
      DATABASE_PASSWORD: appname
      DATABASE_USERNAME: appname
      HISTFILE: /var/www/appname/log/.ash_history
      RAILS_ENV: development
      SMTP_ADDRESS: mailhog
      SMTP_DOMAIN: mailhog
      SMTP_PORT: 1025
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - .:/var/www/appname:cached
      - bundle:/var/www/appname/vendor/bundle
      - node_modules:/var/www/appname/node_modules
      - rails_cache:/var/www/appname/tmp/cache
      - packs:/var/www/appname/public/packs

  mailhog:
    image: mailhog/mailhog:v1.0.0

  mysql:
    environment:
      MYSQL_HISTFILE: /var/www/appname/log/.mysql_history
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    image: mysql:5.7.27
    volumes:
      - ./containers/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./log:/var/www/appname/log
      - mysql:/var/lib/mysql

volumes:
  bundle:
  mysql:
  node_modules:
  rails_cache:
  packs:
