default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  database: <%= ENV.fetch('DATABASE_NAME') %>_<%= Rails.env %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>_<%= Rails.env %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
