default: &default
  address: <%= ENV['SMTP_ADDRESS'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION']&.to_sym || 'plain' %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] || 'true' %>
  openssl_verify_mode: <%= ENV['SMTP_OPENSSL_VERIFY_MODE'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  port: <%= ENV['SMTP_PORT'] %>
  user_name: <%= ENV['SMTP_USER_NAME'] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
